package(default_visibility = ["//visibility:public"])

java_test(
    name = "neuron_layer",
    srcs = ["NeuronLayerTest.java"],
    test_class = "com.vgalloy.neuron.neuronlayer.NeuronLayerTest",
    deps = [
        "//src/main/java:src",
    ],
    testonly = False,
)
